version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis_for_bot
    restart: always

  bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - GROUP_ID=${GROUP_ID}
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - bot_network

  web:
    build: ./web
    container_name: web_panel
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge