version: "3.8"

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=你的TG机器人TOKEN
      - ADMIN_ID=你的TG ID
      - GROUP_ID=你的群ID
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
