services:
  redis:
    image: redis:latest
    container_name: redis-for-bot
    restart: always

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nahida.bot
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    command: python bot.py

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web_panel
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - redis
    command: python web.py
